using Escherize.Geometry;
using Escherize.Io;

namespace Escherize.Tests;

/// <summary>
/// The four fixed test shapes of SPEC §8.7, generated by this helper into
/// <c>tests/fixtures</c> so that the regression snapshots always run on the same input.
/// </summary>
internal static class TestFixtures
{
    /// <summary>The names of the fixtures, in snapshot order.</summary>
    public static IReadOnlyList<string> Names { get; } = ["star", "lshape", "narrowwaist", "cat"];

    /// <summary>The directory the fixtures live in.</summary>
    /// <returns>The absolute path.</returns>
    public static string Directory()
    {
        // The test assembly runs from bin/<config>/<tfm>, four levels below the project.
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !System.IO.Directory.Exists(Path.Combine(directory.FullName, "fixtures")))
        {
            directory = directory.Parent;
        }

        if (directory is null)
        {
            throw new DirectoryNotFoundException("The tests/fixtures directory was not found.");
        }

        return Path.Combine(directory.FullName, "fixtures");
    }

    /// <summary>Writes any fixture that is missing, and returns the path of one.</summary>
    /// <param name="name">The fixture name.</param>
    /// <returns>The path of the fixture file.</returns>
    public static string EnsureWritten(string name)
    {
        string directory = Directory();
        System.IO.Directory.CreateDirectory(directory);

        string path = Path.Combine(directory, $"{name}.json");
        if (!File.Exists(path))
        {
            PolygonReader.WriteJson(path, Build(name));
        }

        return path;
    }

    /// <summary>Builds one fixture shape.</summary>
    /// <param name="name">The fixture name.</param>
    /// <returns>The polygon, counter-clockwise.</returns>
    /// <exception cref="ArgumentException">The name is not one of the four fixtures.</exception>
    public static Vec2[] Build(string name) => name switch
    {
        "star" => Star(),
        "lshape" => TestShapes.LShape(),
        "narrowwaist" => NarrowWaist(),
        "cat" => Cat(),
        _ => throw new ArgumentException($"There is no fixture named '{name}'.", nameof(name)),
    };

    /// <summary>A five pointed star.</summary>
    /// <returns>The outline.</returns>
    public static Vec2[] Star()
    {
        var points = new Vec2[10];
        for (int i = 0; i < points.Length; i++)
        {
            double radius = i % 2 == 0 ? 1.0 : 0.42;
            double angle = (2 * Math.PI * i / points.Length) + (Math.PI / 2);
            points[i] = new Vec2(radius * Math.Cos(angle), radius * Math.Sin(angle));
        }

        return PolygonOps.EnsurePositiveOrientation(points);
    }

    /// <summary>
    /// A long shape with a narrow waist, in the spirit of a country outline (SPEC §8.7).
    /// </summary>
    /// <returns>The outline.</returns>
    public static Vec2[] NarrowWaist()
    {
        var points = new List<Vec2>();
        const int Steps = 60;

        // Two lobes joined by a thin neck, traced as an outline of varying half width.
        for (int i = 0; i <= Steps; i++)
        {
            double t = -1.0 + (2.0 * i / Steps);
            points.Add(new Vec2(t * 3.0, HalfWidth(t)));
        }

        for (int i = Steps; i >= 0; i--)
        {
            double t = -1.0 + (2.0 * i / Steps);
            points.Add(new Vec2(t * 3.0, -HalfWidth(t)));
        }

        return PolygonOps.EnsurePositiveOrientation(
            PolygonOps.RemoveConsecutiveDuplicates([.. points], 1e-9));

        static double HalfWidth(double t) => 0.15 + (0.85 * t * t * t * t);
    }

    /// <summary>A rounded body with two ears, in the spirit of a cat (SPEC §8.7).</summary>
    /// <returns>The outline.</returns>
    public static Vec2[] Cat()
    {
        var points = new List<Vec2>();
        const int Steps = 96;

        for (int i = 0; i < Steps; i++)
        {
            double angle = 2 * Math.PI * i / Steps;
            double radius = 1.0;

            // Two bumps near the top of the outline stand in for the ears.
            foreach (double ear in (double[])[Math.PI / 3, 2 * Math.PI / 3])
            {
                double distance = Math.Abs(WrapAngle(angle - ear));
                radius += 0.55 * Math.Exp(-distance * distance / (2 * 0.16 * 0.16));
            }

            points.Add(new Vec2(radius * Math.Cos(angle), 0.85 * radius * Math.Sin(angle)));
        }

        return PolygonOps.EnsurePositiveOrientation([.. points]);
    }

    /// <summary>Wraps an angle into the range minus pi to pi.</summary>
    /// <param name="angle">The angle in radians.</param>
    /// <returns>The wrapped angle.</returns>
    private static double WrapAngle(double angle)
    {
        while (angle > Math.PI)
        {
            angle -= 2 * Math.PI;
        }

        while (angle < -Math.PI)
        {
            angle += 2 * Math.PI;
        }

        return angle;
    }
}
